resources:
  - ../../base
patches:
  - path: patch-env.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: app
images:
  - name: docker.io/gothicfan/app
    digest: sha256:dab55dac9c62ef4eca286090ad2e7144102047a591f69f4ca772f80749d69df2
  - name: docker.io/gothicfan/internal-service
    digest: sha256:4e413b94bc60b5272c14128753d5f0a7a8f0d97c7f8dc73e8d8cbbc950e9254a
